# Generated by Django 3.1.2 on 2021-05-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
